# invalid -n which is over max, but as signed int32 is positive
PLAYER1="HUMAN"
PLAYER2="HUMAN"
OVERRIDE_ARGS="-n 4500000000 -k 1"
export GUI_ERROR_CODE=0
MINIMUM_DURATION=0
TIMEOUT=4
EXPECTED_GAME_ERROR_CODE=1
NO_GUI_ARGS_CHECK=1
NO_DIFF_CHECK=1
