# ai vs ai, 1 turn of doing nothing
PLAYER1="MOCK"
PLAYER2="MOCK"
N=9
K=1
S=1
P1=1,1
P2=1,9
export AI1_ERROR_CODE=1
export AI2_ERROR_CODE=1
export GUI_ERROR_CODE=0
TIMEOUT=4
MINIMUM_DURATION=1
EXPECTED_GAME_ERROR_CODE=0
