# -n with text-only text argument
PLAYER1="HUMAN"
PLAYER2="HUMAN"
OVERRIDE_ARGS="-n tekst -k 1"
export GUI_ERROR_CODE=0
MINIMUM_DURATION=0
TIMEOUT=4
EXPECTED_GAME_ERROR_CODE=1
NO_GUI_ARGS_CHECK=1
NO_DIFF_CHECK=1
